---
title: "Visualization session"
author: "Kristine Henriksen"
date: "17/6/2021"
output: html_document
---
```{r setup}
source(here::here("R/package-loading.R")) #load packages
load(here::here("data/nhanes_small.rda")) #load data
```

# One variable plots

```{r continuous-variables}
# good plots for continuous variables
# density plot
ggplot(nhanes_small, aes(x = bmi)) +
    geom_density()

# histogram
ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()


```

```{r discrete-variables}
# good plots for continuous variables
# barplots
ggplot(nhanes_small, aes(x = sex)) + 
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()

```

```{r removing-NA-values}
nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))
# save the new tidied dataset in our data folder
usethis::use_data(nhanes_tidied, overwrite = TRUE)

ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()

```

# Two variable plots

```{r two-continous-variables}
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))
# scatter plot
bmi_chol + 
    geom_point()

# scatter plot, but with hexagons
bmi_chol +
    geom_hex()

# Runs a smoothing line with confidence interval
bmi_chol +
    geom_smooth()

bmi_chol + 
    geom_hex() +
    geom_smooth()
```

```{r two.discrete variables}
two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex))
# barplot of two discrete variables (stacked)
two_discrete +
    geom_bar()
    
# barplot of two discrete variables (not stacked)
two_discrete +
    geom_bar(position = position_dodge())

```

```{r plotting-dicrete-and-continuous-variables-together}
two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

# boxplot
two_mixed +
    geom_boxplot()

# Not hiding data using a jitter plot
two_mixed + 
    geom_jitter()

# Show the distribution with a violin plot
two_mixed + 
    geom_violin()

```


# Exercise to make plots with one or two variables

```{r exercise-11-5}
# 1a. Distribution of age
ggplot(nhanes_tidied, aes(x = age)) +
    geom_density()

ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_density()

ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_point()

ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_smooth()

ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex() + 
    geom_smooth()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_point()

ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()

ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_smooth()

ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex() + 
    geom_smooth()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

nhanes_tidied %>% 
    drop_na(phys_active) %>% 
    ggplot(aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_jitter()

ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()
```


# Plotting three or more variables

```{r using-colour}
# Question: Is systolic blood pressure different in those with or without diabetes in females and males?
# one continuous, two discrete 

nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) + 
    geom_boxplot()

nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) + 
    geom_violin()


#Question: How does BMI relate to systolic blood pressure and age?
# three continuous 
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) + 
    geom_point()


#Question: How does BMI relate to systolic blood pressure, and what is different between those with and without diabetes? 
# two continuous and one discrete
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) + 
    geom_point()

```

```{r using-faceting}
# Plot BMI in relation to systolic blood pressure and diabetes status using

# faceting by column (side-by-side)
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() +
    facet_grid(cols = vars(diabetes))

# faceting by row (stacked)
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() +
    facet_grid(rows = vars(diabetes))

# 5 variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) + 
    geom_point() +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex))

```


# Exercise for changing colours

```{r exercise-discrete-variables}
# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

base_barplot +
    scale_fill_viridis_d()
```






















